package com.baojk.we.dao.mapper;

import com.baojk.we.dao.model.ArticleImg;
import com.baojk.we.dao.model.ArticleImgExample;
import com.baojk.we.dao.model.ArticleImgKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface ArticleImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    int countByExample(ArticleImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    int deleteByExample(ArticleImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ArticleImgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    int insert(ArticleImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    int insertSelective(ArticleImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    List<ArticleImg> selectByExample(ArticleImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    ArticleImg selectByPrimaryKey(ArticleImgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ArticleImg record, @Param("example") ArticleImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ArticleImg record, @Param("example") ArticleImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleImg record);
}