package com.baojk.we.dao.mapper;

import com.baojk.we.dao.model.VisitRecord;
import com.baojk.we.dao.model.VisitRecordExample;
import com.baojk.we.dao.model.VisitRecordKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface VisitRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    int countByExample(VisitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    int deleteByExample(VisitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(VisitRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    int insert(VisitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    int insertSelective(VisitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    List<VisitRecord> selectByExample(VisitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    VisitRecord selectByPrimaryKey(VisitRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VisitRecord record, @Param("example") VisitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VisitRecord record, @Param("example") VisitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VisitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VisitRecord record);
}