spring:
  application:
    name: we
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://23.106.130.113:3306/we?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&allowMultiQueries=true
    username: root
    password: Bwg23114.
    name: druid
  druid:
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT　'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  resources:
    add-mappings: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    dispatch-options-request: true
    static-path-pattern: /**
  profiles:
    active: local
  session:
    store-type: none
#threads:
#  pool:
#    queueCapacity: 50
#    corePoolSize: 5
#    maxPoolSize: 50
#    keepAliveSeconds: 60
jedis:
  pool:
    host: 23.106.130.113
    port: 6379
#logging:
#  config: classpath:logback-spring.xml
#  path: logs/
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9000/eureka/  #注册中心地址
server:
  port: 9999
  servlet:
    context-path: /we